# fly.toml app configuration file generated for africado on 2026-02-16

app = "africado-consulting"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    IDEGIN_CLOUD_SECRET_KEY = "sk_17717019_mlwpmb6c_iGmzHk_tZ06sQpxabwifq2DJbRLxxSZ1wh8w-EN3sHo"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
